// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6f_-P0lvQ_wlc8GzD3Z2q3BHIoZpvSgc',
    appId: '1:432730221079:web:3dcd5ab38c069f8899ca52',
    messagingSenderId: '432730221079',
    projectId: 'mypath-7f4dc',
    authDomain: 'mypath-7f4dc.firebaseapp.com',
    storageBucket: 'mypath-7f4dc.firebasestorage.app',
    measurementId: 'G-K2QMXS7XJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHhliK0tjmIRtve1g3i3tGBxrhekpafTM',
    appId: '1:432730221079:android:ff402a20f1966f4e99ca52',
    messagingSenderId: '432730221079',
    projectId: 'mypath-7f4dc',
    storageBucket: 'mypath-7f4dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7uIZewBiouIC5hbui79l6oliKM8IjipQ',
    appId: '1:432730221079:ios:4d9bd793a62cdae599ca52',
    messagingSenderId: '432730221079',
    projectId: 'mypath-7f4dc',
    storageBucket: 'mypath-7f4dc.firebasestorage.app',
    iosBundleId: 'com.example.mypath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7uIZewBiouIC5hbui79l6oliKM8IjipQ',
    appId: '1:432730221079:ios:4d9bd793a62cdae599ca52',
    messagingSenderId: '432730221079',
    projectId: 'mypath-7f4dc',
    storageBucket: 'mypath-7f4dc.firebasestorage.app',
    iosBundleId: 'com.example.mypath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6f_-P0lvQ_wlc8GzD3Z2q3BHIoZpvSgc',
    appId: '1:432730221079:web:9830d5e8a241620799ca52',
    messagingSenderId: '432730221079',
    projectId: 'mypath-7f4dc',
    authDomain: 'mypath-7f4dc.firebaseapp.com',
    storageBucket: 'mypath-7f4dc.firebasestorage.app',
    measurementId: 'G-TYK6FVXNMQ',
  );
}
